version: '3.8'
services:
  django:
    image: jignaciocc/ecent-pro-backend:latest
    ports:
      - "8000:8000"
      - "5020:5020"
    networks:
      - modbus-net
    volumes:
      - django_media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./alert_rules.yml:/app/alert_rules.yml
      - ./alertmanager.yml:/app/alertmanager.yml
      - ./prometheus_multiproc:/tmp/prometheus_multiproc
      - ./compiled_mibs:/app/compiled_mibs
      - ./uploaded_mibs:/app/uploaded_mibs
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FRONTEND_BASE_URL=http://192.168.100.11
      - DJANGO_SETTINGS_MODULE=ecent.settings
      - PYTHONPATH=/app
      - JWT_SECRET=tusupersecretoclave
      - LICENSE_EXPIRATION_DATE=2025-12-31 23:59:59
      - DATABASE_NAME=ecent
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=Teknica1!
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    devices:
      - "/dev:/dev"
    privileged: true
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: ecent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Teknica1!
      PG_MAX_CONNECTIONS: 300
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - modbus-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ecent"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: jignaciocc/ecent-pro-frontend:latest
    ports:
      - "80:80"
    networks:
      - modbus-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - django
    restart: always

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - modbus-net
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./prometheus_multiproc:/tmp/prometheus_multiproc
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    ports:
      - "9090:9090"
    networks:
      - modbus-net
    depends_on:
      - django
    restart: always

  grafana:
    image: grafana/grafana:11.2.4
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/config/img/grafana_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    networks:
      - modbus-net
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - modbus-net
    restart: always

  celery:
    image: jignaciocc/ecent-pro-backend:latest
    command: celery -A ecent worker -l info
    depends_on:
      - django
      - redis
      - postgres
    environment:
      - PYTHONPATH=/app
      - JWT_SECRET=tusupersecretoclave
      - LICENSE_EXPIRATION_DATE=2025-12-31 23:59:59
      - DJANGO_SETTINGS_MODULE=ecent.settings
      - DATABASE_NAME=ecent
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=Teknica1!
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    volumes:
      - django_media:/app/media
      - ./prometheus_multiproc:/tmp/prometheus_multiproc
      - ./compiled_mibs:/app/compiled_mibs
      - ./uploaded_mibs:/app/uploaded_mibs
    networks:
      - modbus-net
    devices:
      - "/dev:/dev"
    privileged: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery-beat:
    image: jignaciocc/ecent-pro-backend:latest
    command: celery -A ecent beat -l info
    depends_on:
      - celery
      - redis
      - postgres
    environment:
      - PYTHONPATH=/app
      - JWT_SECRET=tusupersecretoclave
      - LICENSE_EXPIRATION_DATE=2025-12-31 23:59:59
      - DJANGO_SETTINGS_MODULE=ecent.settings
      - DATABASE_NAME=ecent
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=Teknica1!
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    volumes:
      - django_media:/app/media
      - ./prometheus_multiproc:/tmp/prometheus_multiproc
      - ./compiled_mibs:/app/compiled_mibs
      - ./uploaded_mibs:/app/uploaded_mibs
    networks:
      - modbus-net
    devices:
      - "/dev:/dev"
    privileged: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  # -------------------------------------------------------------------------
  # DB BACKUP AUTOMÁTICO
  # -------------------------------------------------------------------------
  db-backup:
    build:
      context: ./db-backup
    container_name: db-backup
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Teknica1!
      POSTGRES_DB: ecent
    volumes:
      - ./backups:/backups
    networks:
      - modbus-net
    restart: unless-stopped

networks:
  modbus-net:
    driver: bridge

volumes:
  django_media:
  prometheus_data:
  postgres_data:
  grafana_data:
